version: '2'

services:
  db:
    image: postgres:9.3

  impala:
    build: ./impala
    links:
      - "db:postgres"

  ibis:
    build: ./ibis-docker
    links:
      - "db:postgres"
      - "impala:impala"
      - "impala:hdfs"
